[[this_includes]]
file = 'configurations/common/variables.toml'

[[this_includes]]
file = 'configurations/common/styles.toml'

[[this_includes]]
file = 'configurations/common/samples.toml'
choose = {'samples' = ['mc','intime']}

[output]
path = '/exp/sbnd/app/users/rlazur/spine_anaplot_tools/output/1mu1p/allmuons/'

[analysis]
ordinate_sample = 'mc'
category_branch = 'category'
category_assignment = [[0], [1], [2], [3], [4], [5], [6], [7], [-1,8]]
category_labels = ['Signal', 'uncontained 1p', 'contained Np', 'uncontained Np', 'contained X', 'uncontained X', 'Other $\nu$ CC', 'NC $\nu$', 'Cosmic']
category_colors = ['C0', 'C1', 'red', 'C3', 'C4', 'C5', 'C6', 'C7', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram']


[[figure]]
name = 'flash_time'
type = 'SimpleFigure'
style = 'basic_sbnd_1mu1p'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'flash_time'
yrange = 1.05
draw_kwargs = {'invert_stack_order' = true, 'show_component_number' = true, 'show_component_percentage' = true, 'draw_stat_error' = true}

[[figure]]
name = 'flash_total_short'
type = 'SimpleFigure'
style = 'basic_sbnd_1mu1p'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'flash_total_short'
yrange = 1.05
draw_kwargs = {'invert_stack_order' = true, 'show_component_number' = true, 'show_component_percentage' = true, 'draw_stat_error' = true}

[[figure]]
name = 'flash_total'
type = 'SimpleFigure'
style = 'basic_sbnd_1mu1p'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'flash_total'
yrange = 1.05
draw_kwargs = {'invert_stack_order' = true, 'show_component_number' = true, 'show_component_percentage' = true, 'draw_stat_error' = true}

[[figure]]
name = 'reco_visible_energy'
type = 'SimpleFigure'
style = 'basic_sbnd_1mu1p'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_visible_energy'
yrange = 1.05
draw_kwargs = {'invert_stack_order' = true, 'show_component_number' = true, 'show_component_percentage' = true, 'draw_stat_error' = true}


[[figure]]
name = 'reco_interaction_pt'
type = 'SimpleFigure'
style = 'basic_sbnd_1mu1p'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_interaction_pt'
yrange = 1.05
draw_kwargs = {'invert_stack_order' = true, 'show_component_number' = true, 'show_component_percentage' = true, 'draw_stat_error' = true}




