[[this_includes]]
file = 'configurations/common/variables.toml'

[[this_includes]]
file = 'configurations/common/styles.toml'

[[this_includes]]
file = 'configurations/common/samples.toml'
choose = {'samples' = ['mc','intime']}

[output]
path = '/exp/sbnd/app/users/rlazur/spine_anaplot_tools/output/1mu1p/allmuons'

[analysis]
ordinate_sample = 'mc'
category_branch = 'category'
category_assignment = [[0]]
category_labels = ['']
category_colors = ['C0']
category_types = ['histogram',]


[[figure]]
name = '2D_visible_energy'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra2D', 'xvariable' = 'true_visible_energy', 'yvariable' = 'reco_visible_energy'}]
style = 'basic_sbnd_2d_1mu1p'
draw_kwargs = {'draw_identity' = true}


[[figure]]
name = '2D_interaction_pt'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra2D', 'xvariable' = 'true_interaction_pt', 'yvariable' = 'reco_interaction_pt'}]
style = 'basic_sbnd_2d_1mu1p'
default_figsize = [7.9,6.9]
draw_kwargs = {'draw_identity' = true}