[[this_includes]]
file = 'configurations/common/variables.toml'

[[this_includes]]
file = 'configurations/common/styles.toml'

[[this_includes]]
file = 'configurations/common/samples.toml'
choose = {'samples' = ['mc','intime']}

[output]
path = '/exp/sbnd/app/users/rlazur/spine_anaplot_tools/output/1mu1p/contained'

[analysis]
ordinate_sample = 'mc'
category_branch = 'category'
category_assignment = [[0]]
category_labels = ['']
category_colors = ['C0']
category_types = ['histogram',]


[[figure]]
name = '2D_visible_energy'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra2D', 'xvariable' = 'true_visible_energy', 'yvariable' = 'reco_visible_energy'}]
style = 'basic_sbnd_2d_1mu1p'
draw_kwargs = {'draw_identity' = true}


[[figure]]
name = '2D_interaction_pt'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra2D', 'xvariable' = 'true_interaction_pt_2d', 'yvariable' = 'reco_interaction_pt_2d'}]
style = 'basic_sbnd_2d_1mu1p'
draw_kwargs = {'draw_identity' = true}

[[figure]]
name = 'visible_energy_projection'
type = 'SimpleFigure'
style = 'basic_sbnd_2d_1mu1p'
xtitle = '(Reco-True)/True'
[[figure.artists]]
type = 'SpineSpectra2D'
xtitle = '(Reco-True)/True | Visible Energy'
xvariable = 'true_visible_energy_2d'
yvariable = 'reco_visible_energy_2d'
xrange = [-0.6,0.2]
draw_kwargs = {'show_option' = 'projection', 'fit_type' = 'crystal_ball'}


[[figure]]
name = 'deltapt_projection'
type = 'SimpleFigure'
style = 'basic_sbnd_2d_1mu1p'
xtitle = '(Reco-True)/True'
[[figure.artists]]
type = 'SpineSpectra2D'
xtitle = '(Reco-True)/True | deltaPt'
xvariable = 'true_interaction_pt_2d'
yvariable = 'reco_interaction_pt_2d'
xrange = [-1, 10]
draw_kwargs = {'show_option' = 'projection', 'fit_type' = 'gaussian'}